baseURL: /
languageCode: en-us
title: Jasonelle
theme: hugo-fresh

params:
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Jasonelle
    # Hero subtitle (optional)
    subtitle: Create iOS, Android and Web Apps with JSON
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "/docs"
    # Hero image (from /images/___)
    image: illustrations/worker.svg
    # Footer logos (from /images/logos/clients/___.svg)
    clientlogos: []
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Home
    url: /
  - title: Docs
    url: /docs
  - title: Github
    url: https://github.com/jasonelle/jasonelle
  
  section1:
    title: Jasonelle Family
    subtitle: Components that would bring you joy!
    tiles:
    - title: Jasonette
      icon: mobile-feed
      text: Make Native iOS and Android apps with JSON.
      url: /docs
      buttonText: Get started
    - title: Cell.js
      icon: laptop-cloud
      text: Create amazing web apps using JSON Cells.
      url: /docs
      buttonText: Get started
    - title: SelectTransform.js
      icon: plug-cloud
      text: Create your own JSON template languages!.
      url: /docs
      buttonText: Get started
  section2:
    title: Why use JSON to create Apps?
    subtitle: Because it's awesome.
    features:
    - title: Powerful and unified language
      text: JSON is an industry standard today. Computers can understand it and humans too!. You can always use transpilers like hjson to ease development.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Easy to learn
      text: By using a simple language like JSON you can learn and implement faster. Saving time and delivering more results.
      icon: doc-sync
    - title: Huge Ecosystem
      text: Nearly every software today supports JSON. Finding professionals and creating tools that understands JSON will be a piece of cake!.
      icon: mouse-globe
  section3:
    title: Deliver results
    subtitle: easier, faster, happier
    image: demo-jasonette.gif
    buttonText: Get started
    buttonLink: "/docs"
  section4:
    title: Jasonelle's Reviews
    subtitle: 
    clients:
    - name: Christian M.
      quote: With Jasonette I finished my Android prototype in record time for my University project!.
      job: Developer
      img: 2
    - name: Camilo C.
      quote: Jasonelle brings me joy!. It's a wonderful and innovative way of crafting apps.
      job: Sofware Forgemaster
      img: 3
    - name: You
      quote: Jasonelle Family Rulz!.
      job: Awesome Human
      img: 1
  footer:
    # Logo (from /images/logos/___)
    logo: ninja.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/jasonelle/jasonelle
      # Icons are from Font Awesome
      icon: github
    bulmalogo: true